### ISSUE TITLE
Additional informations on Farmer lots

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#36]
For specific reportings to the authorities we need to integrate additional informations for each farmer lot.

1) the date of the purchase by the buying agent from the farmer. This date may differ from the delivery to our warehouse.

2) the number of bags we puchased from the farmer. Let this be a simple numeric field.

**Comment by treviser** [comment]
@candidroot This 2 fields have only informational purpose and must be entered manually for each lot at the creation of the lot.

**Comment by candidroot** [comment]
@treviser 
Hello we add two field in stock production lot form view please have look and let me know is there any update ..
thanks

**Comment by treviser** [comment]
![image](https://user-images.githubusercontent.com/1814941/135623194-3acb2428-eb71-44eb-accd-7ecea8ece335.png)

It is ok in the stock production lot form, but for easy entering the data, we need it in the receipt form detailed operation.

**Comment by treviser** [comment]
@dastcaboz Please check and mark as solved if successful:

![image](https://user-images.githubusercontent.com/1814941/135802999-4e33ef5f-6e04-4c7e-a663-afcfc493a5e9.png)

**Comment by candidroot** [comment]
@treviser 
Hello Here we can use same two new field  which define in  "stock production lot" 
So for that you need to select lot_id in "Detailed Operation" instead of use Lot/Serial Number Name,
You can configure from below screen shot

![image](https://user-images.githubusercontent.com/39722234/135804392-c3bc3c6a-14c8-4f37-bd25-708ead8ca2f5.png)

Please let me know for more updates...

**Comment by treviser** [comment]
@candidroot 
I do not really understand what you mean. I have created a new PO00059 for Magasin Carrière which does not have ticked the option "User Existing Lots/Serial Numbers". I have successfully entered the Lot00115 with a purchasing date and a number of bags. 

When I then see the LOT00115 in the Inventory App Master Data, the date and bags are not available:

![image](https://user-images.githubusercontent.com/1814941/135811081-864122b3-e14d-4499-bd05-9696d4aec76b.png)

**Comment by dastcaboz** [comment]
Looks good to me. Just some small corretions for more user comfort.
<img width="1440" alt="Bildschirmfoto 2021-10-04 um 08 47 59" src="https://user-images.githubusercontent.com/90847414/135811844-c88459c0-1ebb-4de6-ba5b-091c5f1b464e.png">

**Comment by candidroot** [comment]
@treviser 
please take latest pull and check it
thanks

**Comment by dastcaboz** [comment]
Layout is now much better.

Still issues:

1) Lot number should not be editable but created automatically by odoo.
<img width="1440" alt="Bildschirmfoto 2021-10-04 um 12 09 51" src="https://user-images.githubusercontent.com/90847414/135833583-7f52bbe5-777d-438b-a247-af11e3c83bc4.png">


2) After saving the form, the date of purchase and the number of bags disappear again.
<img width="1440" alt="Bildschirmfoto 2021-10-04 um 12 08 49" src="https://user-images.githubusercontent.com/90847414/135833606-17d63974-823c-488b-b07c-9af2530c548b.png">

**Comment by dastcaboz** [comment]
The bags and the purchase date do not appear in mobile view.

![Bildschirmfoto 2021-10-04 um 12 23 41](https://user-images.githubusercontent.com/90847414/135851256-e53aa60a-cedc-477b-a5e2-00ba3a98e42a.png)

**Comment by candidroot** [comment]
@treviser 
I committed code please take latest pull and upgrade module then check it,
is there any issue then let me know,
thanks

**Comment by treviser** [comment]
@candidroot As far as I remember, it works on the test database, but we urgently have to fix the problem with updating the app on the prod database caboz2

**Comment by treviser** [comment]
@dastcaboz Can you please check on caboz2 without polluting the prod database?

**Comment by dastcaboz** [comment]
Seems to work. 
![Issue #36](https://user-images.githubusercontent.com/90847414/139663484-7e7a68c7-1304-4a2a-9403-5c0a891f5a6b.jpg)

**Comment by dastcaboz** [comment]
But is still not properly displayed in mobile view. The subform in the tap "Detailled operation" is invisible.


![IMG_5A80943CA12F-1](https://user-images.githubusercontent.com/90847414/139664298-cc6ea5ce-2872-46fe-84c7-ec5fc7e10354.jpeg)
